import pandas as pd

df = pd.read_csv("/home/esem5377/lg_aimers9_ws/lg_aimers9_ws/open/data/train.csv", encoding="utf-8-sig")
print("shape:", df.shape)
print()
print("target balance:")
print(df["control_success"].value_counts(dropna=False, normalize=True))
print()
print("season range:", df["season"].min(), df["season"].max())
print(df.groupby("season").size())
print()
print("missing ratio (top 20):")
print((df.isna().mean().sort_values(ascending=False) * 100).head(20))
print()
print("dtypes:")
print(df.dtypes)
print()
for c in ["top_bottom", "game_type", "base_state", "pitcher_hand", "batter_hand"]:
    print(c, df[c].unique()[:10])
print()
print("pitcher_id nunique:", df["pitcher_id"].nunique())
print("batter_id nunique:", df["batter_id"].nunique())
print("pitcher_team_id nunique:", df["pitcher_team_id"].nunique())
print("batter_team_id nunique:", df["batter_team_id"].nunique())
